import { useEffect, useState } from 'react';
import Spinner from '../components/Spinner';
import ExportButton from '../components/ExportButton';
import { getReports, getReportCatalogue, createReport, deleteReport, toReportView, canAccess } from '../lib/api';

export default function Reports({ currentUser }) {
  const canWrite = canAccess(currentUser?.role, 'reports', 'write');

  const [reports, setReports] = useState([]);
  const [catalogue, setCatalogue] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [generating, setGenerating] = useState('');
  const [deletingId, setDeletingId] = useState(null);

  const load = () => getReports().then((dtos) => setReports(dtos.map(toReportView)));

  useEffect(() => {
    Promise.all([load(), getReportCatalogue().then(setCatalogue)])
      .catch((err) => setError(err.message || 'Failed to load reports.'))
      .finally(() => setLoading(false));
  }, []);

  const generate = async (type) => {
    setGenerating(type);
    setError('');
    try {
      await createReport({ type, generatedBy: currentUser?.displayName || '' });
      await load();
    } catch (err) {
      setError(err.message || 'Failed to generate report.');
    } finally {
      setGenerating('');
    }
  };

  const remove = async (id) => {
    if (!window.confirm('Delete this report?')) return;
    setDeletingId(id);
    try {
      await deleteReport(id);
      setReports((prev) => prev.filter((r) => r.entityId !== id));
    } catch (err) {
      setError(err.message || 'Failed to delete report.');
    } finally {
      setDeletingId(null);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {error && <div style={{ padding: '8px 12px', background: '#FBE7E5', color: '#A6362E', borderRadius: 8, fontSize: 12.5 }}>{error}</div>}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 12 }}>
        {catalogue.map((r) => (
          <div key={r.type} style={{ background: '#FFFFFF', border: '1px solid #D7E4E1', borderRadius: 12, padding: 16, display: 'flex', flexDirection: 'column', gap: 6 }}>
            <div style={{ fontSize: 13.5, fontWeight: 700 }}>{r.name}</div>
            <div style={{ fontSize: 12, color: '#52685F' }}>{r.description}</div>
            {canWrite && (
              <button
                onClick={() => generate(r.type)}
                disabled={generating === r.type}
                style={{ alignSelf: 'flex-start', marginTop: 6, padding: '7px 14px', background: '#1F6E72', color: '#fff', border: 'none', borderRadius: 8, fontWeight: 600, fontSize: 12, cursor: generating === r.type ? 'default' : 'pointer', opacity: generating === r.type ? 0.7 : 1, display: 'flex', alignItems: 'center', gap: 7 }}
              >
                {generating === r.type && <Spinner size={12} color="#fff" />}
                {generating === r.type ? 'Generating…' : 'Generate'}
              </button>
            )}
          </div>
        ))}
      </div>

      <div style={{ background: '#FFFFFF', border: '1px solid #D7E4E1', borderRadius: 12, overflow: 'hidden' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 16px', borderBottom: '1px solid #D7E4E1' }}>
          <div style={{ fontSize: 12.5, fontWeight: 700 }}>Recently generated</div>
          <ExportButton label="Excel" filename="reports" sheet="Reports" rows={() => reports.map((r) => ({ Name: r.name, 'Generated by': r.by || '', Date: r.date }))} />
        </div>
        {loading && <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: 16, fontSize: 13, color: '#78908A' }}><Spinner size={14} />Loading…</div>}
        {!loading && reports.length === 0 && (
          <div style={{ padding: 16, fontSize: 13, color: '#78908A' }}>No reports generated yet.</div>
        )}
        {reports.map((r) => (
          <div key={r.entityId} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '11px 16px', borderBottom: '1px solid #E9F1EF', fontSize: 13 }}>
            <div>{r.name}</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, color: '#78908A' }}>
              <span>{r.by || '—'} · {r.date}</span>
              {canWrite && (deletingId === r.entityId
                ? <Spinner size={12} />
                : <button type="button" onClick={() => remove(r.entityId)} style={{ border: 'none', background: 'transparent', color: '#A6362E', fontSize: 11, fontWeight: 700, cursor: 'pointer' }}>Delete</button>)}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
